Moving downloaded binaries to bin folder

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -7,6 +7,10 @@ set -euo pipefail
 ASDF_INSTALL_TYPE=${ASDF_INSTALL_TYPE:-version  }
 
 install() {
+
+  local bin_install_path="$ASDF_INSTALL_PATH/bin"
+  local bin_path="${bin_install_path}/trip"
+
   # shellcheck disable=SC1091
   source "$(dirname "$0")/download"
   download "${ASDF_INSTALL_VERSION}" "${ASDF_INSTALL_PATH}"
@@ -14,12 +18,13 @@ install() {
     mv "${ASDF_INSTALL_PATH}/trip.exe" "${ASDF_INSTALL_PATH}/trip"
   fi
   chmod +x "${ASDF_INSTALL_PATH}/trip"
+  mv "${ASDF_INSTALL_PATH}/trip" "${bin_path}"
 
   if [ -x "$ASDF_INSTALL_PATH/trip" ]; then
     echo "trip ${ASDF_INSTALL_VERSION} has been installed"
     exit 0
   else
-    echo "An error ocurred while installing trippy $ASDF_INSTALL_VERSION" 1>&2
+    echo "An error ocurred while installing trippy ${ASDF_INSTALL_VERSION}" 1>&2
     rm -rf "${ASDF_INSTALL_PATH}/trip"
     exit 1
   fi
