Simplifying installation process (#3)
* Working github actions with hardcoded installers for Ubuntu and MacOS.
* Updated README with issues.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -7,28 +7,31 @@ set -euo pipefail
 ASDF_INSTALL_TYPE=${ASDF_INSTALL_TYPE:-version  }
 
 install() {
-  # shellcheck disable=SC1091
-  source "$(dirname "$0")/download"
 
   local bin_install_path="$ASDF_INSTALL_PATH/bin"
   local bin_path="${bin_install_path}/trip"
 
-  mkdir -p "$bin_path"
+  # shellcheck disable=SC1091
+  source "$(dirname "$0")/download"
   download "${ASDF_INSTALL_VERSION}" "${ASDF_INSTALL_PATH}"
-
-  if [[ -f "${ASDF_INSTALL_PATH}/trippy" ]]; then
-    mv "${ASDF_INSTALL_PATH}/trip" "${bin_path}"
-    mv "${ASDF_INSTALL_PATH}/trip.exe" "${bin_path}"
+  if [[ -f "${ASDF_INSTALL_PATH}/trip.exe" ]]; then
+    mv "${ASDF_INSTALL_PATH}/trip.exe" "${ASDF_INSTALL_PATH}/trip"
   fi
-  chmod +x "${bin_path}"
-  rm -rf "${ASDF_INSTALL_PATH}/trip*"
+  chmod +x "${ASDF_INSTALL_PATH}/trip"
+  mkdir -p "${bin_install_path}"
+  mv "${ASDF_INSTALL_PATH}/trip" "${bin_install_path}"
 
-  if [ -x "$ASDF_INSTALL_PATH/bin/trip" ]; then
-    echo "trip $ASDF_INSTALL_VERSION has been installed"
+  if [ -x "${bin_path}" ]; then
+    echo "trip ${ASDF_INSTALL_VERSION} has been installed"
     exit 0
   else
-    echo "An error ocurred while installing trippy $ASDF_INSTALL_VERSION" 1>&2
-    rm -rf "${ASDF_INSTALL_PATH}/trip*"
+    echo "An error ocurred while installing trippy ${ASDF_INSTALL_VERSION}" 1>&2
+    if [ -f "${ASDF_INSTALL_PATH}/trip" ]; then
+      rm -rf "${ASDF_INSTALL_PATH}/trip"
+    fi
+    if [ -f "${bin_install_path}/trip" ]; then
+      rm -rf "${bin_install_path}/trip"
+    fi
     exit 1
   fi
 }
